### ISSUE TITLE
cmake error when compiling pcl

### ISSUE THREAD

**Issue by BobbleLaw** [carlosmccosta/dynamic_robot_localization#13]
Hi, thanks for your work.

I encountered an error when I build pcl part, seems like related to cmake version? There is a compiled-from-source pcl-1.9.1 on my system, everything work well.  I am running ROS Kinetic on 16.06. Do you have any idea what might be the problem?
![Screenshot from 2019-11-04 22-52-37](https://user-images.githubusercontent.com/10457678/68131180-8b8caa00-ff57-11e9-8eb4-8fec7dd2c0b3.png)

**Comment by carlosmccosta** [comment]
Good afternoon,

Looking at the console output, it seems that cmake is not able to find the qvtk library with at least version 6.
https://github.com/carlosmccosta/pcl/blob/master-all-pr/cmake/Modules/FindQVTK.cmake#L10

Try installing it and see if it solves your compilation problem:
```
sudo apt-get install qtbase5-dev
sudo apt-get install libvtk6-dev
```

See if these discussions help:
http://www.pcl-users.org/Could-NOT-find-QVTK-td4033527.html
http://unanancyowen.com/en/pcl-with-qt/

P.S.
drl relies on my [fork of pcl](https://github.com/carlosmccosta/pcl), but if you compile drl using the [install scripts](https://github.com/carlosmccosta/dynamic_robot_localization#installation-from-source), it will be created a new workspace and the pcl of my fork should override the one you compiled and also the version from the ubuntu ppa.

Have a nice day :)
