### ISSUE TITLE
HSVto RGB

### ISSUE THREAD

**Issue by sunrentao** [carlosmccosta/dynamic_robot_localization#24]
Dear Carlos,

Thank you for your work on this package.
I pull the newest noetic branch, and I get this error 
`In file included from /home/genius/ros_ws/src/dynamic_robot_localization/src/outlier_detectors/euclidean_outlier_detector.cpp:10:
/home/genius/ros_ws/src/dynamic_robot_localization/include/dynamic_robot_localization/outlier_detectors/impl/euclidean_outlier_detector.hpp: In member function ‘virtual size_t dynamic_robot_localization::EuclideanOutlierDetector<PointT>::detectOutliers(typename pcl::search::KdTree<PointT>::Ptr, const pcl::PointCloud<PointT>&, typename pcl::PointCloud<PointT>::Ptr&, typename pcl::PointCloud<PointT>::Ptr&, double&)’:
/home/genius/ros_ws/src/dynamic_robot_localization/include/dynamic_robot_localization/outlier_detectors/impl/euclidean_outlier_detector.hpp:158:11: error: ‘HSVtoRGB’ is not a member of ‘pcl’
  158 |      pcl::HSVtoRGB(hue, 1.0f, 1.0f, point.r, point.g, point.b);
      |           ^~~~~~~~
`
I installed with your install script. 
And I noticed you pushed a new update related to HSV recently, do you know how this happes ?

Thank you 
Best regards

**Comment by carlosmccosta** [comment]
Hello,

I made improvements to my [pcl fork](https://github.com/carlosmccosta/pcl) and did not push them to github while I was testing them more extensively.
I have now pushed the new commits to my pcl fork -> if you do `roscd pcl && git pull` you should be able to compile without problems.

Have a nice day,
