### ISSUE TITLE
Compile the project once

### ISSUE THREAD

**Issue by abylikhsanov** [carlosmccosta/dynamic_robot_localization#8]
Compiling on ARM takes a lot of time, especially PCL! What is the best way to compile PCL once for all and save its binaries and libraries so I can simply transfer to another ARM machine? I tried to simply make the PCL independently and then install its binaries to some folder and use that but getting an error at:

```
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /opt/ros/melodic/share/dynamic_reconfigure/cmake/dynamic_reconfigure-macros.cmake:80 (add_custom_target):
  add_custom_target cannot create target "pcl_ros_gencfg" because another
  target with the same name already exists.  The existing target is a custom
  target created in source directory "/home/abyl/right-wheel/src/laser_icp".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  perception_pcl/pcl_ros/CMakeLists.txt:70 (generate_dynamic_reconfigure_options)

```

**Comment by carlosmccosta** [comment]
Good morning :)

You can use catkin to create an "installable" version of the packages.

For enabling it in a catkin_tools workspace:
`catkin config --install`

For disabling it:
`catkin config --no-install`

More info:
[https://catkin-tools.readthedocs.io/en/latest/verbs/catkin_config.html#installing-packages](https://catkin-tools.readthedocs.io/en/latest/verbs/catkin_config.html#installing-packages)

The older catkin_make can also generate the install space:

[http://wiki.ros.org/catkin/Tutorials/using_a_workspace#Installing_Packages](http://wiki.ros.org/catkin/Tutorials/using_a_workspace#Installing_Packages)

You can also generate a deb package from the install space for making it easier to install.
There are several ways to achieve this:
* [bloom](http://wiki.ros.org/bloom)
  * [https://answers.ros.org/question/173804/generate-deb-from-ros-package/?answer=173845#post-id-173845](https://answers.ros.org/question/173804/generate-deb-from-ros-package/?answer=173845#post-id-173845)
* [CheckInstall](https://wiki.debian.org/CheckInstall)
* [dpkg-buildpackage](http://manpages.ubuntu.com/manpages/precise/man1/dpkg-buildpackage.1.html)
* [CPack](https://cmake.org/cmake/help/v3.0/module/CPack.html)

**Comment by abylikhsanov** [comment]
Thanks :)  But the error I am getting, do you have an answer for that? Because even if I create a .deb package of your version PCL I might still get that issue

**Comment by carlosmccosta** [comment]
You seem to have in /home/abyl/right-wheel/src/laser_icp a target conflicting with pcl_ros
Both seem to be generating pcl_ros_gencfg.
Check the CMakeLists.txt of laser_icp

**Comment by abylikhsanov** [comment]
Yes but I do not see any conflicts in my CMakeLists, may be you can spot something irregular?

```
cmake_minimum_required(VERSION 2.8.3)
project(laser_icp)

add_compile_options(-std=c++17)

find_package(catkin REQUIRED COMPONENTS
  roscpp
  nodelet
  sensor_msgs
  tf2
  tf2_ros
  pcl_ros
  pcl_conversions
  geometry_msgs
  nav_msgs
)

find_package(catkin REQUIRED)
find_package(PCL REQUIRED)
find_package(PkgConfig)


include_directories(include ${catkin_INCLUDE_DIRS} ${PCL_INCLUDE_DIRS})

catkin_package(
  INCLUDE_DIRS include
  LIBRARIES laser_icp
  CATKIN_DEPENDS roscpp
)
```

**Comment by carlosmccosta** [comment]
The error is pointing at conflicts with dynamic_reconfigure here:
[https://github.com/ros-perception/perception_pcl/blob/melodic-devel/pcl_ros/CMakeLists.txt#L70](https://github.com/ros-perception/perception_pcl/blob/melodic-devel/pcl_ros/CMakeLists.txt#L70)

Unless you removed parts of the cmakelists above, I do not see conflicts.
I normally use a cmake variable for dealing with package dependencies (that should be included in find_package and catkin_depends).
Look here for an example:
[https://github.com/carlosmccosta/dynamic_robot_localization/blob/kinetic-devel/CMakeLists.txt#L10](https://github.com/carlosmccosta/dynamic_robot_localization/blob/kinetic-devel/CMakeLists.txt#L10)

You also have a repeared find_package of catkin and in catkin_package are declaring a library that was not created with add_library (laser_icp).

**Comment by abylikhsanov** [comment]
What parts of the Cmakelists should be removed? Not really clear

**Comment by carlosmccosta** [comment]
Sorry, I meant that it looks like you did not posted the full contents of the cmakelists file.
For example, you declared a library in catkin_package but it was not created with add_library.

**Comment by abylikhsanov** [comment]
Oh okay, but I do not think it causes any errors, here is the rest:
```
add_library(laser_icp src/laser_icp.cpp)

# We don't link against pcl because we are using header only parts
target_link_libraries(laser_icp ${catkin_LIBRARIES})
add_dependencies(laser_icp ${catkin_EXPORTED_TARGETS})

# Nodelet
add_library(laser_icp_nodelet src/laser_icp_nodelet.cpp)
target_link_libraries(laser_icp_nodelet laser_icp)

# Node
add_executable(laser_icp_node src/laser_icp_node.cpp)
target_link_libraries(laser_icp_node laser_icp)

```

So I actually used the Cmake variable to set the ROS packages and used find catkin, like in your example and it worked.. Interesting, does it mean I was declaring them twice which caused the error? I am reading about cmake once more... Never encountered such problem before.

**Comment by carlosmccosta** [comment]
If you deviate from the normal usage of cmakelists.txt and package.xml (such as finding catkin twice, not exporting deps, ...) you may encounter strange errors such as the one you mentioned.

For making you life as pain free as possible, I suggest you follow the advice given in these docs:
* [http://wiki.ros.org/catkin/CMakeLists.txt](http://wiki.ros.org/catkin/CMakeLists.txt)
* [http://wiki.ros.org/catkin/package.xml](http://wiki.ros.org/catkin/package.xml)

**Comment by ghost** [comment]
@abylikhsanov what was the solution? I get this when compiling two projects that both use pcl. If my ROS_WS only contains one project with PCL I do not get this same issue as you.

**Comment by carlosmccosta** [comment]
Hello,

I suggest you create a variable for the package dependencies and use it in `find_package` and `catkin_depends`:

Variable:
https://github.com/carlosmccosta/dynamic_robot_localization/blob/noetic-devel/CMakeLists.txt#L10

Places where to use it:
https://github.com/carlosmccosta/dynamic_robot_localization/blob/noetic-devel/CMakeLists.txt#L39
https://github.com/carlosmccosta/dynamic_robot_localization/blob/noetic-devel/CMakeLists.txt#L86

Have a nice day,
